config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "accounts#new"
  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]
  resources :tokens
  namespace :api, {format: "json"} do
    namespace :v1 do
      get "/timetable", to: "timetable#index"
      namespace :messages do
        get "/list", to: "list#index"
        get "/headlines", to: "headlines#index"
      end
    end
  end
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :account
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :confirm_login

  def index
    @tokens = Token.where(account: @account) #find_byじゃないのね！
  end

  def create
    @new_rand_str = SecureRandom::base58
    @account = Account.find(session[:uid])
    @new_token = Token.new(account: @account, token: @new_rand_str, available: true)
    if @new_token.save
      flash[:notice] = "新しいトークンを作成しました。"
      redirect_to :tokens
    end
  end

  def destroy
    @target_token = Token.find(params[:id])
    @target_token.available = false
    if @target_token.save
      flash[:notice] = "トークンは無効になりました。"
      redirect_to :tokens
    end
  end

  private

  def confirm_login
    if session[:uid] && Account.exists?(id: session[:uid])
      @account = Account.find(session[:uid])
    else
      flash[:alert] = "不正な画面遷移です。もう一度やり直してください。"
      session.delete(:uid)
      redirect_to :root and return
    end
  end
end

app/views/tokens/index.html.erb
<h1>トークン一覧</h1>
<div class="container-user-info">
  <%= @account_student_id %>
  <%= link_to  "ログアウト", session_path(@account), method: :delete %>
</div>
<% if @tokens && @tokens.size > 0 %>
  <table>
    <tbody>
      <tr>
        <th>トークン</th>
        <th>有効状態</th>
      </tr>

        <% @tokens.each do |t| %>
          <tr>
            <td>
              <%= t.token %>
            </td>
            <td>
              <%= t.available ? "有効" : "無効" %>
            </td>
            <% if t.available %>
            <td>
              <%= link_to "無効にする", token_path(t), method: :delete %>
            </td>
            <% end %>
          </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
  関連付けられたトークンはありません。
<% end %>
<%= link_to "新規作成", :tokens, method: :post %>